### ISSUE TITLE
Make storing non-bytes keys friendlier on Python 3

### ISSUE THREAD

**Issue by bbayles** [bbayles/python-pure-cdb#10]
The set of changes required to add Python 3 support (PR #7) mainly involved encoding, of course.

Currently the library handles reading keys like `b'hello'` just fine on Python 3, but keys like `'hello'` produce this not-so-helpful message:

```python
>>> reader.get('hello')
Traceback (most recent call last):
  File "<pyshell#13>", line 8, in <module>
    reader.get('hello')
  File "/home/bo/Code/python-pure-cdb/cdblib/cdblib.py", line 129, in get
    return next(chain(self.gets(key), (default,)))
  File "/home/bo/Code/python-pure-cdb/cdblib/cdblib.py", line 101, in gets
    h = self.hashfn(key) & 0xffffffff
  File "/home/bo/Code/python-pure-cdb/cdblib/djb_hash.py", line 20, in djb_hash
    h = (((h << 5) + h) ^ c) & 0xffffffff
TypeError: unsupported operand type(s) for ^: 'int' and 'str'
```

Rather than just catch the error, I'd like to make it so that string keys can be encoded before queries and inserts. This will entail some minor changes and re-working of the tests.

**Comment by dw** [comment]
Rather than muddying up the reader/writer with isinstance() soup, I'm wondering if this could be done with new helper methods or maybe some facade class, or an "Adaptor" class parameter that handled marshalling keys and values uniformly.. maybe something like:

```python
class Adaptor:
    def load_key(..):
    def load_value(..):
    def dump_key(..)
    def dump_value(..):

class DefaultAdaptor(Adaptor):
    def load_key(key): return key
    ...

class MyAppAdaptor(Adaptor):
    def load_key(key): return key.decode('utf-8')
    def load_value(value): return json.loads(value)

mem = mmap.mmap(..)
r = cdblib.Reader(mem, adaptor=MyAppAdaptor)
```

There are two angles for this I guess. The first is that the more code ends up in get(), the slower lookups become. That's unavoidable.

The other is why this code was ever published :) It was my go to demo of how a complex problem need not mean an ugly implementation, it is/was excellent tutorial code, and I'd like to preserve that if possible.

Any other options?

I'm not fixed to that 'adaptor' idea, its most interesting property is replacing if statements with types, and since you're volunteering the effort ultimately I guess you get to make the call :)

**Comment by dw** [comment]
A better generalization of Adaptor:

```python

class Type:
    def load(..):
    def dump(..):

class DefaultType(Type):
    def load(value): return value
    def dump(value): return value

class TextType:
    def __init__(self, encoding='utf-8'): ..
    def load(value): return value.decode(self.encoding)
    def dump(value): return value.encode(self.encoding)
    
class JsonType(Type):
    def load(value): return json.loads(value)
    def dump(value): return json.dumps(value)


mem = mmap.mmap(..)
r = cdblib.Reader(mem, key_type=cdblib.TextType(), value_type=cdblib.JsonType)
```

**Comment by bbayles** [comment]
Yeah, I'll have to think through this.

I had a similar task in updating [redis-collections](https://github.com/honzajavorek/redis-collections/) to Python 3. In that one we wanted to be able to store arbitrary keys and this used `pickle` for both keys and values. (won't do that here, there's security issues and [this](https://bugs.python.org/issue5518) to contend with).

Your second generalization is a very strong idea; I'll play with it. I wanted to write up this issue so I didn't forget to work on this.

**Comment by bbayles** [comment]
Returning to this after a break - after some playing around, I've added [this branch](https://github.com/dw/python-pure-cdb/compare/non-binary-keys?expand=1), which aims to add some friendliness without mucking things up too badly.

The idea is that `Reader(..., strict=True)` or `Writer(..., strict=True)` can be used to bypass any of the new stuff. This is for when you know your data is all of the `bytes` type and don't want to slow down to avoid errors.

Without `strict=True`, `Reader` and `Writer` will first assume `bytes`-type keys. If that's not a good assumption, they will attempt to coerce the keys to `bytes` using generic encoders.

I'm inclined toward this method instead, as the one [here](https://github.com/dw/python-pure-cdb/issues/10#issuecomment-425773154) is nice, but I'm finding that it clashes with the existing `getint()`, `putint()`, and etc. methods.
