### ISSUE TITLE
Python version of cdbdump

### ISSUE THREAD

**Issue by bbayles** [bbayles/python-pure-cdb#11]
We have a Python version of `cdbmake` that has the functionality of the [original](https://cr.yp.to/cdb/cdbmake.html) and then some.

We could have its inverse as well; a version that supports the 64-bit variants would be useful for CDB manipulation.

**Comment by dw** [comment]
I never needed it for the original project this was for, but I see no reason it shouldn't exist :)

**Comment by bbayles** [comment]
This looks to be [pretty straightforward](https://github.com/dw/python-pure-cdb/compare/python-pure-cdbdump?expand=1); I'll write some tests and make a PR.

**Comment by dw** [comment]
LGTM!
