### ISSUE TITLE
Deprecate using built-in hash() function

### ISSUE THREAD

**Issue by bbayles** [bbayles/python-pure-cdb#12]
As of [Python 3.3](https://docs.python.org/3/reference/datamodel.html#object.__hash__):

> By default, the `__hash__()` values of str, bytes and datetime objects are “salted” with an unpredictable random value. Although they remain constant within an individual Python process, they are not predictable between repeated invocations of Python.

This ruins reading and writing of databases; we should remove this functionality. I think `cdb` files created with Python 2 on different platforms (e.g. 32-bit or ARM) would have a similar issue. 

Notes:
* It's OK to allow for [custom hash functions](https://github.com/dw/python-pure-cdb/blob/e929b6b96fd427c27598b929e8654539f1773f72/cdblib/cdblib.py#L32); we should add a test that shows this in action (maybe with a fast hash like [adler32](https://docs.python.org/3/library/zlib.html#zlib.adler32))
* But we shouldn't provide a method to use the built-in `hash()` in [python-pure-cdbmake](https://github.com/dw/python-pure-cdb/blob/e929b6b96fd427c27598b929e8654539f1773f72/cdblib/cdbmake.py#L8)
* And we should remove the [tests](https://github.com/dw/python-pure-cdb/blob/master/tests/cdblib_test.py#L463) that use built-in `hash()`

**Comment by dw** [comment]
+1

don't think anyone uses it, I just wanted to see how far the code could be pushed perfwise. RIP hash() :)
