### ISSUE TITLE
OSError: [Errno 22] Invalid argument with large files (4-8 GB)

### ISSUE THREAD

**Issue by surfingkaka** [bbayles/python-pure-cdb#26]
python 3.7.1

Mac OS
      Processor Name: Intel Core i5
      Processor Speed: 3.4 GHz
      Number of Processors: 1
      Total Number of Cores: 4
      L2 Cache (per Core): 256 KB
      L3 Cache: 6 MB
      Memory: 8 GB

```
import cdblib
import random
import time
import sys

val = 'a' * 1000000

with open("info.cdb",'wb') as f:
    writer = cdblib.Writer64(f)
    for i in range(9000):
        key = "key1_" + str(random.randint(1,10000))
        writer.put(key.encode(), val.encode())
    writer.finalize()

with open('info.cdb', 'rb') as f:
    data = f.read()
reader = cdblib.Reader64(data)
```

maybe I am missing something.. but I found one so post, could be related

https://stackoverflow.com/questions/48122798/oserror-errno-22-invalid-argument-when-reading-a-huge-file

**Comment by dw** [comment]
Please include the full stack trace, thanks

**Comment by surfingkaka** [comment]
$ python speed_test.py
Traceback (most recent call last):
  File "speed_test.py", line 16, in <module>
    data = f.read()
OSError: [Errno 22] Invalid argument

**Comment by bbayles** [comment]
I'm late to the party here, but [this](https://python-pure-cdb.readthedocs.io/en/latest/library.html#limiting-memory-usage) method provide a useful workaround.
