### ISSUE TITLE
taking over ownership

### ISSUE THREAD

**Issue by dw** [bbayles/python-pure-cdb#29]
Hi @bbayles,

I've been trimming my GitHub quite aggressively recently, and wondered if it maybe made sense to revisit transferring this repo over to you -- you've already been the sole maintainer for quite some time :)

The old address will still redirect to the new owner if it is transferred, so nothing is lost, but for me a tangible sense of freedom is gained! Let me know if it suits, otherwise I can close this ticket down

**Comment by bbayles** [comment]
I'm game - go ahead and do the transfer. Many thanks!

**Comment by dw** [comment]
>  bbayles/python-pure-cdb already exists 

Can you rename / delete your existing fork? GitHub doesn't like it :)

**Comment by bbayles** [comment]
> Your repository "bbayles/python-pure-cdb" was successfully deleted. 

There you go; we'll try that again.

**Comment by dw** [comment]
And away it goes! Thanks a million for picking up work on the library, you've done a fantastic job :)

**Comment by bbayles** [comment]
Thanks! Would you mind making me owner on PyPI?
