### ISSUE TITLE
Value is not found when key's hash == 0

### ISSUE THREAD

**Issue by pwlodarczyk92** [bbayles/python-pure-cdb#39]
The problem is exactly as stated in the title. Example code that reproduces the problem:
```python
import tempfile
import cdblib
key1 = b'xyz'
key2 = bytes([*[13, 168, 240, 240, 64, 64, 128, 128, 128, 0, 128, 128, 0, 0, 0, 128, 128], *([0]*692791), 128])
value = b'abc'
f = tempfile.TemporaryFile('r+b')
w = cdblib.Writer(f)
w.put(key1, value)
w.put(key2, value)
w.finalize()
f.seek(0)
r = cdblib.Reader(file_obj=f)
print(r.get(key1) == value)
print(r.get(key2) == value)
```
produces the output:
```
True
False
```
It's probably because empty slots are detected in the `gets` method based on the hash value, instead of it's position:
```python
                rec_h, rec_pos = self.read_pair(
                    self.data[pos:pos+self.pair_size]
                )

                if not rec_h:
                    break
                elif rec_h == h:
                    ...
```

Thanks for working on this package!

**Comment by bbayles** [comment]
Apologies for the delay; I somehow got unsubscribed from issues in this repo...

Nice catch, and thanks for providing the test case.

I've opened https://github.com/bbayles/python-pure-cdb/pull/43, which includes this test case.

**Comment by dw** [comment]
Nice catch!
