### ISSUE TITLE
question about compatibility

### ISSUE THREAD

**Issue by bjmgeek** [bbayles/python-pure-cdb#40]
Are the 64 bit cdb files that this tool creates compatible with other implementations?  e.g. https://github.com/chrislusf/cdb64 ?

**Comment by bbayles** [comment]
I downloaded the `test.cdb` file [here](https://github.com/chrislusf/cdb64/blob/master/test/test.cdb) and tried to read it with this library. Alas, it didn't work.

If that's not the right file to test, let me know!
