### ISSUE TITLE
pip support

### ISSUE THREAD

**Issue by h5rdly** [bbayles/python-pure-cdb#5]
Hi,

First, thanks for this nice dbm package .

I was wondering if you could add "pippability", so users of scripts (like the one I'm writing :)) that use python-pure-cdb could just pip install it and carry on. 

I hope it's ok to ask, as I'm not familiar with the process. . Is this a daunting task?

Thanks

**Comment by dw** [comment]
I'm extremely busy with work. Would you care to submit a pull request for
setup.py? Once/if it's in a good state then let me know and I'll trigger
the upload. Thanks, David

**Comment by dw** [comment]
Hi :)

The package was already on PyPI, I had just forgotten. I've uploaded the current code as pure-cdb==2.0.0, so you should just be able to "pip install pure-cdb" to get cdblib. All the best,


David
